from uppi.domain.canone_models import CanoneInput, CanoneResult


def classify_zona(microzona: str, foglio: str) -> int: ...
def classify_subfascia(canone_mq: float, zona: int, tipologia: str) -> int: ...
def get_base_range_euro_mq(zona: int, subfascia: int, tipologia: str) -> tuple[float,float]: ...
def apply_variations(canone_base: float, input: CanoneInput) -> CanoneResult: ...